<?php

namespace SV\ReportImprovements\SV\AdvancedBbCodesPack\BbCode\Tag;

use function is_callable;

/**
 * @extends \SV\AdvancedBbCodesPack\BbCode\Tag\Bimg
 */
class Bimg extends XFCP_Bimg
{
    public function render(array $tagChildren, $tagOption, array $tag, array $options)
    {
        if (!empty($options['svDisableUrlMediaTag']))
        {
            if (is_callable([$this->renderer, 'renderTagUrl']))
            {
                return $this->renderer->renderTagUrl($tagChildren, $tagOption, $tag, $options);
            }

            return $this->renderer->renderUnparsedTag($tag, $options);
        }

        return parent::render($tagChildren, $tagOption, $tag, $options); // TODO: Change the autogenerated stub
    }
}